blank_issues_enabled: true
contact_links:
  - name: Feature Proposals
    url: https://github.com/pyscript/pyscript/discussions/new?category=proposals
    about: Create a feature request to make PyScript even better
  - name: Questions
    url: https://github.com/pyscript/pyscript/discussions/new?category=q-a
    about: For questions or discussions about pyscript
