name: Test Report
on:
    workflow_run:
        workflows: ['\[CI\] Build Unstable']
        types:
            - completed
jobs:
    report:
        runs-on: ubuntu-latest
        steps:
            - uses: dorny/test-reporter@v1.6.0
              with:
                  artifact: test_results
                  name: Test reports
                  path: "*.xml"
                  reporter: java-junit
