// ⚠️ Part of this file is automatically generated
//    The :RUNTIMES comment is a delimiter and no code should be written/changed after
//    See rollup/build_runtimes.cjs to know more

import { base } from "./runtime/_utils.js";

/** @type {Map<string, object>} */
export const registry = new Map();

/** @type {Map<string, object>} */
export const configs = new Map();

/** @type {string[]} */
export const selectors = [];

/** @type {string[]} */
export const prefixes = [];

export const runtime = new Proxy(new Map(), {
    get(map, id) {
        if (!map.has(id)) {
            const [type, ...rest] = id.split("@");
            const runtime = registry.get(type);
            const url = /^https?:\/\//i.test(rest)
                ? rest[0]
                : runtime.module(...rest);
            map.set(id, {
                url,
                module: import(url),
                engine: runtime.engine.bind(runtime),
            });
        }
        const { url, module, engine } = map.get(id);
        return (config, baseURL) =>
            module.then((module) => {
                configs.set(id, config);
                const fetch = config?.fetch;
                if (fetch) base.set(fetch, baseURL);
                return engine(module, config, url);
            });
    },
});

const register = (runtime) => {
    for (const type of [].concat(runtime.type)) {
        registry.set(type, runtime);
        selectors.push(`script[type="${type}"]`);
        prefixes.push(`${type}-`);
    }
};

//:RUNTIMES
import micropython from "./runtime/micropython.js";
import pyodide from "./runtime/pyodide.js";
import ruby from "./runtime/ruby.js";
import wasmoon from "./runtime/wasmoon.js";
for (const runtime of [micropython, pyodide, ruby, wasmoon]) register(runtime);
