name: "[CI] Test"

on:
    push: # Only run on merges into main that modify files under pyscriptjs/ and examples/
        branches:
            - main
        paths:
            - pyscript.core/**
            - .github/workflows/test.yml # Test that workflow works when changed

    pull_request: # Run on any PR that modifies files under pyscriptjs/ and examples/
        branches:
            - main
        paths:
            - pyscript.core/**
            - .github/workflows/test.yml # Test that workflow works when changed
    workflow_dispatch:

jobs:
    BuildAndTest:
        runs-on: ubuntu-latest-8core
        env:
            MINICONDA_PYTHON_VERSION: py38
            MINICONDA_VERSION: 4.11.0
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Cache node modules
              uses: actions/cache@v3
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - name: setup Miniconda
              uses: conda-incubator/setup-miniconda@v2

            - name: Setup Environment
              run: make setup

            - name: Build
              run: make build

            - name: Integration Tests
              run: make test-integration-parallel

            - uses: actions/upload-artifact@v3
              with:
                  name: pyscript
                  path: |
                      pyscript.core/dist/
                  if-no-files-found: error
                  retention-days: 7

            - uses: actions/upload-artifact@v3
              if: success() || failure()
              with:
                  name: test_results
                  path: test_results/
                  if-no-files-found: error
